app:
  env: "development"

server:
  host: "localhost"
  port: "8080"
  trusted_proxies:
  mode: "debug" # test, release

database:
  uri: "mongodb://localhost:27017"
  name: "bobshop"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

cookie:
  http_only: true
  secure: false
  same_site: "none" # strict

auth:
  jwt:
    secret: ""
    expiration_hours: 72
